version: 0.0
os: linux
files:
    - source: /docker-compose.yml
      destination: /home/ubuntu/SKN04-4th-3Team
file_exists_behavior: OVERWRITE

permissions:
    - object: /home/ubuntu
      pattern: '**'
      owner: root
      group: root

hooks:
    AfterInstall:
        - location: scripts/after_deploy.sh
          timeout: 100000  # 100초
          runas: root